# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-25 20:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_user_poked'),
        ('poke', '0002_poke_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='PokeRef',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('pokeeref', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='PokeeRef', to='login.User')),
                ('poker', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='PokerRef', to='login.User')),
            ],
        ),
        migrations.RemoveField(
            model_name='poke',
            name='poker',
        ),
    ]
