# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-25 21:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poke', '0004_poke_poker'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokeref',
            name='count',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
